import { expect, test } from "@playwright/test";

test("a new login finds unfinished work and answers its saved question", async ({browser, request}) => {
  await request.post("http://127.0.0.1:8419/__research_fixture/reset");
  const context = await browser.newContext();
  const first = await context.newPage();
  const errors: string[] = [];
  first.on("pageerror", error => errors.push(error.message));
  await first.goto("http://127.0.0.1:8419/research");
  await first.getByRole("button", {name:"登入並開始探索"}).click();
  await first.getByLabel("想探索什麼風味？").fill("果香");
  await first.getByRole("button", {name:"開始探索"}).click();
  await expect(first.getByText("你指的是哪個版本？")).toBeVisible();
  const taskUrl = first.url();
  expect(taskUrl).toMatch(/\/research\/[0-9a-f-]{36}$/);
  await first.close();

  const reopened = await context.newPage();
  reopened.on("pageerror", error => errors.push(error.message));
  await reopened.goto("http://127.0.0.1:8419/research");
  await reopened.getByRole("button", {name:"登入並開始探索"}).click();
  const resume = reopened.getByRole("link", {name:"繼續上次探索"});
  await expect(resume).toHaveAttribute("href", new URL(taskUrl).pathname);
  await resume.click();
  await reopened.getByRole("button", {name:"登入查看委託"}).click();
  await expect(reopened.getByText("你指的是哪個版本？")).toBeVisible();
  await reopened.getByLabel("15 年").click();
  await reopened.getByRole("button", {name:"送出答覆"}).click();
  await expect(reopened.getByText("已依補充版本重新查核")).toBeVisible();
  await reopened.getByLabel("這次沒有適合的").check();
  await reopened.getByLabel("選擇理由").fill("合成測試：目前沒有適合的候選");
  await reopened.getByRole("button",{name:"保存探索結論"}).click();
  await expect(reopened.getByText("探索結論已保存。")).toBeVisible();
  await reopened.close();
  const savedPage=await context.newPage();
  savedPage.on("pageerror",error=>errors.push(error.message));
  await savedPage.goto("http://127.0.0.1:8419/plans/00000000-0000-4000-8000-000000000014/conclusions");
  await savedPage.getByRole("button",{name:"登入查看保存結論"}).click();
  await expect(savedPage.getByText("合成測試：目前沒有適合的候選")).toBeVisible();
  await expect(savedPage.getByText("未重新查詢前，不代表仍符合目前預算或價格。")).toBeVisible();
  expect(errors).toEqual([]);
  await context.close();
});
